
server:
  port: 8005
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
      - id: currency-conversion
        uri: lb://currency-conversion-service
        predicates:
        - Path=/currency-converter-feign/**
      - id: currency-exchange
        uri: lb://currency-exchange-service
        predicates:
        - Path=/currency-exchange/**
management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway

logging:
    level:
        reactor:
            netty: INFO
        org:
            springframework:
                cloud:
                    gateway: INFO